### ISSUE TITLE
AnyPets

### ISSUE THREAD

**Issue by EvGeniyLell** [yunhao/Crystal#7]
Sorry I didn’t found AnyPets repository. So I will write this my issue. The issue with decimal separator. Can you read it from settings? Now if decimal separator is not “,” user can not  add/edit weight.

**Comment by yunhao** [comment]
Thanks for your feedback. After some investigations, I find out what was causing the problem. 

I have made some fixes and the new version will be available on App Store soon.

**Comment by EvGeniyLell** [comment]
Thank! I will wait for it.
